# https://taskfile.dev

version: '3'

vars:
  AWS_ACCOUNT:
    sh: echo $AWS_ACCOUNT_ID
  AWS_PROFILE:
    sh: echo $AWS_PROFILE
  AWS_REGION:
    sh: echo $AWS_REGION
  ACTIONS_FILE_PATH:
    sh: echo $PWD/actions

includes:
  nuke:
    taskfile: ./cdk-base/nuke-account/Taskfile.yaml
    dir: ./cdk-base/nuke-account
  bootstrap:
    taskfile: ./cdk-base/bootstrap/Taskfile.yaml
    dir: ./cdk-base/bootstrap
  common:
    taskfile: ./cdk-base/common/Taskfile.yaml

tasks:
  docs:
    dir: ./docs
    cmds:
      - drawio -x -f png -o arc.png arc.drawio
    silent: true

  build:
    cmds:
      - scripts/build-go.sh $PWD/src

  deploy-custom-resources:
    deps:
      - build
    dir: ./infrastructure
    cmds:
      - npm ci
      - cdk synth
      - cdk deploy CustomResourceStack
